apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: coupon
  labels:
    app: eshop
    service: coupon
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /coupon-api
        pathType: Prefix
        backend:
          service:
            name: coupon-api
            port:
              number: 80
