apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webspa
  labels:
    app: eshop
    service: webspa
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  {{- if eq .Values.protocol "https" }}
  tls:
  - hosts:
      - {{ .Values.host }}
    secretName: tls-secret
  {{- end }}
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: webspa
            port:
              number: 80
