apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webstatus
  labels:
    app: eshop
    service: webstatus
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - http:
      paths:
      - path: /webstatus(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: webstatus
            port:
              number: 80
