apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basket
  labels:
    app: eshop
    service: basket
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /basket-api
        pathType: Prefix
        backend:
          service:
            name: basket-api
            port:
              number: 80
